default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: 'development'
  host: localhost
  username: sk

test:
  <<: *default
  database: 'test'
  host: localhost
  username: sk

production:
  <<: *default
  database: 'production'
